### PR TITLE
add missing files for #8

### PR DESCRIPTION
**Pull request by jomo**
completes #8

### CODE REVIEW

**Comment by jengel3** [comment]
[Looks good!](http://sponge.jake0oo0.me/users/Jake0oo0) Thanks! Now time to work on getting the Minotaur stuff working, that's a really good idea.

**Comment by jomo** [comment]
should be really easy. we only need to add an IGN column to users. We probably want to store the UUID as well, but I'm not sure if Minotar supports that yet. Might fork that as well :)

**Comment by jomo** [comment]
Apparently minotar doesn't have UUID support yet, see minotar/minotar#69.

**Comment by jengel3** [comment]
Shouldn't be that hard to add a UUID option to minotar, hopefully we can PR that at some point.

**Pull request merged**
